# Enable powerlevel10k
POWERLEVEL9K_MODE='nerdfont-complete'
source "$ZDOTDIR/config.d/plugins/p10k.zsh"

# Cache a tool's init script — otherwise regenerated by forking the tool
# on every startup — keyed on the tool's resolved path. Used by fzf.zsh
# and zoxide.zsh. Keying on the path (not mtime) is deliberate: nix pins
# store-file mtimes to the epoch, so `binary -nt cache` can never see an
# upgrade, whereas the store path changes on every version bump.
#   $1 = cache file basename   $2 = command name   $3… = command that
#   prints the init script (e.g. `fzf --zsh`).
_zsh_cache_eval() {
    local cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/$1" name=$2
    shift 2
    local bin=${commands[$name]}
    [[ -n $bin ]] || return          # tool not installed — skip init
    bin=${bin:A}                     # resolve symlink → real store path
    local stamp="#@ $bin" first=''
    [[ -s $cache ]] && IFS= read -r first < $cache
    if [[ $first != $stamp ]]; then
        [[ -d ${cache:h} ]] || mkdir -p ${cache:h}
        { print -r -- $stamp; "$@" } >| $cache
    fi
    source $cache
}

# Enable Iterm2 shell integration. Pre-seed $iterm2_hostname so the
# integration doesn't fork `hostname -f` on every prompt — on macOS it
# deliberately doesn't cache the FQDN (~8ms/prompt here). Computed once
# per shell; a mid-session hostname change (VPN attach) only affects the
# RemoteHost badge until the next new shell.
iterm2_hostname=${iterm2_hostname:-$(hostname -f 2>/dev/null)}
source "$ZDOTDIR/config.d/plugins/iterm2_shell_integration.zsh"
