# Enable powerlevel10k
POWERLEVEL9K_MODE='nerdfont-complete'
source "$ZDOTDIR/config.d/plugins/p10k.zsh"

# Cache a tool's init script — otherwise regenerated by forking the tool
# on every startup. Used by fzf.zsh and zoxide.zsh. The cache is keyed on
# the tool's resolved path, its mtime and size, and the generator command:
# the path changes on a
# nix upgrade (store mtimes are epoch-pinned, so `-nt` can't see those),
# while mtime+size additionally catch an in-place upgrade (cargo/apt)
# that reuses the path. zstat is a builtin, so the stamp stays fork-free.
#   $1 = cache file basename   $2 = command name   $3… = command that
#   prints the init script (e.g. `fzf --zsh`).
_zsh_cache_eval() {
    local cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/$1" name=$2
    shift 2
    local bin=${commands[$name]}
    [[ -n $bin ]] || return          # tool not installed — skip init
    bin=${bin:A}                     # resolve symlink → real store path
    local -A st
    zmodload -F zsh/stat b:zstat 2>/dev/null && zstat -H st -- $bin 2>/dev/null
    # Fold the generator command ($@, after the shift 2) into the stamp so
    # editing a flag here (e.g. `fzf --zsh` → `fzf --zsh --no-foo`) invalidates
    # the cache even when the binary is unchanged. Single-line by construction:
    # both callers' args contain no newlines.
    local stamp="#@ $bin ${st[mtime]:-0} ${st[size]:-0} ${(j: :)@}" first=''
    [[ -s $cache ]] && IFS= read -r first < $cache
    if [[ $first != $stamp ]]; then
        [[ -d ${cache:h} ]] || mkdir -p ${cache:h}
        # Generate into a temp file and swap it in atomically — and only if
        # BOTH the generator exits 0 AND the rename lands. Writing the live
        # cache directly would let a failed/partial `fzf --zsh` be stamped as
        # success forever; an unchecked mv would (on a read-only target — an
        # ACL/immutable bit, or $cache occupied by a dir) go on to source a
        # STALE cache for a changed binary, or hit `source: no such file` on
        # first init, and leak the temp. On either failure keep the previous
        # good cache; if there's none, skip init this round.
        local tmp=$cache.tmp.$$
        if { print -r -- $stamp; "$@" } >| $tmp && mv -f -- $tmp $cache; then
            zcompile -R -- $cache 2>/dev/null   # source below uses the .zwc
        else
            rm -f -- $tmp
            print -u2 "zsh: $name init/cache-install failed; keeping previous cache"
            [[ -s $cache ]] || return
        fi
    fi
    # Bytecode revalidation, independent of the stamp: the stamp keys on the
    # binary + args, not $ZSH_VERSION, so after a zsh upgrade $cache.zwc still
    # embeds the old version and zsh silently reparses $cache text every
    # startup (the stamp still matches, so no regen fires above). Rebuild the
    # .zwc from the existing text cache — no tool fork — when it's unloadable.
    # On the regen path above this is a no-op (freshly valid). Same stdout
    # chatter caveat as antidote.zsh, hence >/dev/null 2>&1.
    [[ -f $cache.zwc ]] && ! zcompile -t -- $cache.zwc >/dev/null 2>&1 \
        && zcompile -R -- $cache 2>/dev/null
    source $cache
}

# Enable Iterm2 shell integration. Pre-seed $iterm2_hostname so the
# integration doesn't fork `hostname -f` on every prompt — on macOS it
# deliberately doesn't cache the FQDN (~8ms/prompt here). Computed once
# per shell; a mid-session hostname change (VPN attach) only affects the
# RemoteHost badge until the next new shell.
iterm2_hostname=${iterm2_hostname:-$(hostname -f 2>/dev/null)}
source "$ZDOTDIR/config.d/plugins/iterm2_shell_integration.zsh"
